### ISSUE TITLE
Move all videos to CFL youtube channel and embed youtube video

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-portal-backend#292]
Now that we have a YouTube space we need to migrate the videos that exist on our site so that they are all in one place.

**Comment by lauracumming** [comment]
Also add to Gitbook

**Comment by faucomte97** [comment]
@lauracumming I'm not sure what this entails, which videos do we have "on our site"?
Also, add to Gitbook how, and where?

And - why is this task in the portal-react repo?

**Comment by lauracumming** [comment]
Can we move any videos we link to at Ocado Technology YouTube to Code for Life Youtube please?

**Comment by faucomte97** [comment]
You mean change the host channel on YouTube?

**Comment by lauracumming** [comment]
Yeah, but not sure you can at the mo. I have requested the account is changed to a Brand account.

**Comment by lauracumming** [comment]
We can upload and add links to Gitbook still though. some schools can't view YouTube so we need to add them to relevant pages as uploads too.

**Comment by faucomte97** [comment]
We can upload videos to Gitbook?
Do we have the original video files?

**Comment by lauracumming** [comment]
Still awaiting update on channel from YouTube

**Comment by faucomte97** [comment]
Asked about downloading videos of OT channel

**Comment by faucomte97** [comment]
Asked RM to download videos and send them to this folder https://drive.google.com/drive/folders/11LXdmu1cC41uY6CiU_9pFlZ1i2wRWHd7
